export interface ExerciseData {
  name: string;
  youtubeVideoId: string;
}

export const EXERCISE_LIBRARY: ExerciseData[] = [
  // Warmup & Mobility
  { name: "Jumping Jacks", youtubeVideoId: "1b98mvZH4a8" },
  { name: "High Knees", youtubeVideoId: "D0_K4_5fC4k" },
  { name: "Butt Kicks", youtubeVideoId: "RUYdbl_vQ0A" },
  { name: "Arm Circles", youtubeVideoId: "O2n0_K_jG4" },
  { name: "Leg Swings", youtubeVideoId: "da_K-S-d15Q" },
  { name: "Torso Twists", youtubeVideoId: "s3qSf_c9_aA" },
  { name: "Cat-Cow Stretch", youtubeVideoId: "K9hTf_b-pLI" },
  { name: "World's Greatest Stretch", youtubeVideoId: "wzL1S2_kLgA" },
  { name: "Inchworms", youtubeVideoId: "ZY2ji_c_gQk" },
  { name: "Neck Rolls", youtubeVideoId: "s-24_e_g7NA" },
  { name: "Shoulder Rolls", youtubeVideoId: "V2x3olGg_gE" },
  { name: "Hip Circles", youtubeVideoId: "2GLr_A4N2Lg" },
  { name: "Scapular Push-ups", youtubeVideoId: "a-32_eYgPM" },
  { name: "Ankle Rotations", youtubeVideoId: "a-sxVfJ0a4" },
  { name: "Jump Rope", youtubeVideoId: "_0p2Gj_Ff4" },

  // Boxing Technique & Footwork
  { name: "Shadow Boxing", youtubeVideoId: "mAJ2o_Jp_h4" },
  { name: "Boxing Jab-Cross", youtubeVideoId: "2n6tW1i5g_A" },
  { name: "Boxing Hooks", youtubeVideoId: "tOLEaIg3_jI" },
  { name: "Boxing Uppercuts", youtubeVideoId: "sKcfH_Aso_8" },
  { name: "Slip Rope Drills", youtubeVideoId: "iSSqOkd_k9U" },
  { name: "Bob and Weave", youtubeVideoId: "lW5pBVI1e7I" },
  { name: "Pivot Steps", youtubeVideoId: "32h9z3yG-J8" },
  { name: "Defensive Slips", youtubeVideoId: "aZg-sU3QT2o" },
  { name: "Defensive Rolls", youtubeVideoId: "BmaBP84Rk0A" },
  { name: "Jab-Cross-Hook Combo", youtubeVideoId: "7PyoGoa42Qc" },
  { name: "Body Shots", youtubeVideoId: "fO0k_s1lZAc" },
  { name: "Footwork Ladder Drills", youtubeVideoId: "zjwWSHr7C9s" },
  { name: "Heavy Bag Drills", youtubeVideoId: "QhTBFj2AgGk" },
  { name: "Double End Bag Drills", youtubeVideoId: "mY7o0xY_s5o" },
  { name: "Cone Drills", youtubeVideoId: "tqum10c-k0E" },

  // Strength - Upper Body
  { name: "Push-ups", youtubeVideoId: "IODxDxX7oi4" },
  { name: "Pull-ups", youtubeVideoId: "eGo4IYlbE5g" },
  { name: "Chin-ups", youtubeVideoId: "brhRXlOhsAM" },
  { name: "Overhead Press", youtubeVideoId: "_RlRDWO2jfg" },
  { name: "Bent-Over Rows", youtubeVideoId: "vT2GjY_Umpw" },
  { name: "Medicine Ball Slams", youtubeVideoId: "JpYyY-S_c2U" },
  { name: "Landmine Press", youtubeVideoId: "wZ2a9h92a08" },
  { name: "Diamond Push-ups", youtubeVideoId: "J0DnG1_S_k8" },
  { name: "Dips", youtubeVideoId: "2z8JmcrW-PY" },
  { name: "Renegade Rows", youtubeVideoId: "6SPN3-rTDO0" },
  { name: "Incline Dumbbell Press", youtubeVideoId: "8iPEnn-ltC8" },
  { name: "Face Pulls", youtubeVideoId: "eIq5CB9InCU" },

  // Strength - Lower Body
  { name: "Barbell Squats", youtubeVideoId: "bEv6CCg2BC8" },
  { name: "Deadlifts", youtubeVideoId: "ytGaGIn3SjE" },
  { name: "Alternating Lunges", youtubeVideoId: "QOVaHwm-Q6U" },
  { name: "Bulgarian Split Squats", youtubeVideoId: "2C-uNgN5n_4" },
  { name: "Glute Bridges", youtubeVideoId: "wPMvIomG3O8" },
  { name: "Calf Raises", youtubeVideoId: "JbyjN43vo_8" },
  { name: "Goblet Squats", youtubeVideoId: "MeWEEy3Q9DU" },
  { name: "Romanian Deadlifts (RDLs)", youtubeVideoId: "JCXUYuzwNrM" },
  { name: "Walking Lunges", youtubeVideoId: "L8fvypoCDGQ" },
  { name: "Kettlebell Swings", youtubeVideoId: "s4iX4D03e2I" },

  // Strength - Core
  { name: "Plank", youtubeVideoId: "pD3bKbP_fJI" },
  { name: "Crunches", youtubeVideoId: "Xyd_fa5zoEU" },
  { name: "Leg Raises", youtubeVideoId: "l4kQd9eWclE" },
  { name: "Russian Twists", youtubeVideoId: "wkD8rjkodUI" },
  { name: "Bicycle Crunches", youtubeVideoId: "9FGilKjmh_s" },
  { name: "Flutter Kicks", youtubeVideoId: "ANVdMDa4eMI" },
  { name: "Hanging Leg Raises", youtubeVideoId: "1A3k_a-pTaQ" },
  { name: "Ab Rollouts", youtubeVideoId: "vGR-62d2oaE" },
  { name: "Medicine Ball Twists", youtubeVideoId: "IlliN82-aYA" },
  { name: "Side Plank", youtubeVideoId: "Zfi_c2E2v2A" },
  { name: "V-Ups", youtubeVideoId: "iP2fjvG_rAU" },
  { name: "Hollow Body Hold", youtubeVideoId: "v_n_9oBw0dg" },
  { name: "Pallof Press", youtubeVideoId: "c_G-h_g-wmk" },
  { name: "Cable Wood Chops", youtubeVideoId: "p33aH_A2L7c" },
  { name: "Bird-Dog", youtubeVideoId: "wiFNA3sqjCA" },

  // Plyometrics & Conditioning
  { name: "Burpees", youtubeVideoId: "dZgVxmf6jkA" },
  { name: "Squat Jumps", youtubeVideoId: "U4s4mEQ5VqU" },
  { name: "Mountain Climbers", youtubeVideoId: "nmwgirg2B5s" },
  { name: "Box Jumps", youtubeVideoId: "52r_1_Yy9p0" },
  { name: "Lunge Jumps", youtubeVideoId: "t-AnS3-h9-s" },
  { name: "Broad Jumps", youtubeVideoId: "6-A3x3a3Y0E" },
  { name: "Tuck Jumps", youtubeVideoId: "ZHble-1_Q1s" },
  { name: "Battle Ropes", youtubeVideoId: "s3b25V24-mI" },
  { name: "Sled Pushes", youtubeVideoId: "T-4T2k5Gces" },
  { name: "Sprints", youtubeVideoId: "Ge3g-mO1y-A" },
  { name: "Jump Rope High Knees", youtubeVideoId: "w-3A3Ie87yI" },
  { name: "Kettlebell Snatches", youtubeVideoId: "y25A-p90c30" },
  { name: "Medicine Ball Chest Pass", youtubeVideoId: "UaYp36Q2Lw8" },
  { name: "Medicine Ball Overhead Throws", youtubeVideoId: "zVus21pISI4" },
  { name: "Lateral Box Jumps", youtubeVideoId: "D_9Jt-h06-U" },

  // Cool-down & Flexibility
  { name: "Quad Stretch", youtubeVideoId: "s2j2-p-BOA4" },
  { name: "Hamstring Stretch", youtubeVideoId: "H3NfK_2dglg" },
  { name: "Triceps Stretch", youtubeVideoId: "R-83s_GfNfk" },
  { name: "Chest Stretch", youtubeVideoId: "NSn3G2I7V4I" },
  { name: "Child's Pose", youtubeVideoId: "2v-A0v_n_Ak" },
  { name: "Glute Stretch", youtubeVideoId: "iCZdo3GItgo" },
  { name: "Pigeon Pose", youtubeVideoId: "5-5Y_3yL4p4" },
  { name: "Cobra Pose", youtubeVideoId: "JDcdhTuycOI" },
  { name: "Downward Dog", youtubeVideoId: "j97SSGsnWu4" },
  { name: "Lying Knee-to-Chest Stretch", youtubeVideoId: "i195n5svdjo" },
  { name: "Cross-Body Shoulder Stretch", youtubeVideoId: "Lp7-S0_1CqM" },
  { name: "Figure-Four Stretch", youtubeVideoId: "2j_A-P-hdUo" },
  { name: "Butterfly Stretch", youtubeVideoId: "kO40_S012fE" },
  { name: "Spinal Twist", youtubeVideoId: "As3m9LnpV4Y" },
  { name: "Calf Stretch", youtubeVideoId: "7G5WKB2wQ3c" },
];
